dataset:
  config_file: tmp/config/dataset_config.yaml
  override:
    num_samples: null
  selected:
  - gsm8k
model:
  device_map: cuda:0
  dtype: float16
  name: /home/lulu/Green_AI/quantized/Llama-3.2-3B-Instruct-asvd95quantnone-alpha60_rank128-awq-4bit-20260225_171834
  trust_remote_code: true
quantization:
  enabled: false
  framework: awq
  methods:
    awq:
      modules_to_not_convert: []
      output_dir: null
      q_group_size: 128
      version: gemm
      w_bit: 4
      zero_point: true
    bnb:
      bits: 4
      bnb_4bit_compute_dtype: bfloat16
      bnb_4bit_quant_type: nf4
      bnb_4bit_use_double_quant: true
      llm_int8_enable_fp32_cpu_offload: false
      llm_int8_has_fp16_weight: false
      llm_int8_skip_modules:
      - lm_head
      llm_int8_threshold: 6.0
      output_dir: null
    gptq:
      act_group_aware: false
      bits: 4
      calib_num: 1024
      damp_auto_increment: 0.01
      damp_percent: 0.05
      desc_act: true
      group_size: 128
      lm_head: false
      mse: 0.0
      output_dir: null
      rotation: null
      static_groups: false
      sym: true
      true_sequential: true
      use_eora: false      # 啟用 EoRA
      eora_rank: 32       # 建議先從 32 或 64 開始測試
